export const students = [
 {id:'a1',name:'Sabrina Almeida',grade:'2º',group:'A'}, {id:'a2',name:'Gabriel Costa',grade:'1º',group:'A'},
 {id:'a3',name:'Marina Santos',grade:'3º',group:'A'}, {id:'a4',name:'Lucas Oliveira',grade:'2º',group:'B'},
 {id:'a5',name:'Beatriz Lima',grade:'1º',group:'B'}, {id:'a6',name:'Pedro Souza',grade:'3º',group:'B'}
];
export const initialEvents = [
 {id:'festa',title:'Festa Junina do Externato',type:'Evento',date:'2026-06-20',time:'16:00',place:'Pátio do colégio',audience:'Todos',description:'Resgate demonstrativo pela participação na organização da Festa Junina. Envie um relato para validação.',subject:'Redação',points:0.5,released:true},
 {id:'simulado',title:'Simulado de agosto',type:'Simulado',date:'2026-08-29',time:'08:00',place:'Salas do Ensino Médio',audience:'Todos',description:'A coordenação liberou o resgate para participantes do simulado. Informe sua participação no comprovante.',subject:'Matemática',points:0.5,released:true},
 {id:'e1',title:'Simulado ENEM',type:'Simulado',date:'2026-09-12',time:'08:00',place:'Colégio Externato · salas do Ensino Médio',audience:'Todos',description:'Linguagens, Ciências Humanas e Redação. Leve documento, água e caneta preta.',subject:'Língua Portuguesa',points:0},
 {id:'e2',title:'Prova de Matemática',type:'Prova',date:'2026-09-15',time:'07:30',place:'Sala da turma',audience:'2º A',description:'Geometria espacial: áreas e volumes. Revise as atividades do laboratório.',subject:'Matemática',points:0},
 {id:'e3',title:'Futuros possíveis',type:'Palestra',date:'2026-09-17',time:'10:00',place:'Auditório',audience:'Todos',description:'Uma conversa sobre profissões, escolhas e universidade. Envie sua reflexão após participar.',subject:'Redação',points:0.2},
 {id:'e4',title:'Gincana do conhecimento',type:'Gincana',date:'2026-09-22',time:'13:30',place:'Quadra do colégio',audience:'Todos',description:'Uma missão coletiva de ciência, cultura e solidariedade.',subject:'Redação',points:0.2},
 {id:'e5',title:'Visita ao museu de ciências',type:'Passeio',date:'2026-09-25',time:'07:00',place:'Saída no colégio',audience:'Todos',description:'Inscrição de interesse demonstrativa. A autorização e as orientações de viagem serão feitas pela escola.',subject:'Biologia',points:0.2},
 {id:'e6',title:'Mostra de projetos',type:'Evento',date:'2026-09-29',time:'18:00',place:'Pátio',audience:'Todos',description:'Compartilhe seu projeto com a comunidade escolar.',subject:'Redação',points:0.3}
];
export const labs = {
 geometry:{label:'Geometria espacial',subject:'Matemática',tag:'FORMAS E VOLUMES',instruction:'Gire o prisma e observe cada detalhe.',question:'Qual é o volume deste prisma triangular?',measurements:[['Base do triângulo','6 cm'],['Altura do triângulo','5 cm'],['Comprimento do prisma','10 cm']],answers:['120 cm³','150 cm³','180 cm³'],correct:1,explanation:'A base é um triângulo: (6 × 5) ÷ 2 = 15 cm². Multiplicando pelo comprimento: 15 × 10 = 150 cm³.',hint:'Primeiro calcule a área triangular. Depois multiplique pelo comprimento.',points:0.3},
 chemistry:{label:'Geometria molecular',subject:'Química',tag:'LIGAÇÕES E ESTRUTURAS',instruction:'Explore a molécula de metano, CH₄.',question:'Qual é a geometria molecular do metano?',measurements:[['Átomo central','Carbono'],['Ligações C–H','4'],['Pares livres no carbono','0']],answers:['Trigonal plana','Tetraédrica','Linear'],correct:1,explanation:'Quatro pares de elétrons ligantes se distribuem em uma geometria tetraédrica, com ângulos de aproximadamente 109,5°.',hint:'As quatro ligações procuram ficar o mais afastadas possível no espaço.',points:0.3},
 physics:{label:'Lançamento oblíquo',subject:'Física',tag:'MOVIMENTO E ENERGIA',instruction:'Ajuste o ângulo e explore a trajetória.',question:'Sem resistência do ar e com saída e chegada na mesma altura, qual ângulo maximiza o alcance?',measurements:[['Velocidade inicial','20 m/s'],['Gravidade','10 m/s²'],['Altura inicial e final','0 m']],answers:['30°','45°','60°'],correct:1,explanation:'O alcance é v² × sen(2θ) ÷ g. O seno é máximo quando 2θ = 90°, então θ = 45° e o alcance é 40 m.',hint:'O alcance depende do seno do dobro do ângulo.',points:0.3},
 biology:{label:'Por dentro da célula',subject:'Biologia',tag:'ESTRUTURA E VIDA',instruction:'Gire a célula e observe suas organelas.',question:'Qual organela produz a maior parte do ATP na respiração aeróbia de uma célula eucariótica?',measurements:[['Modelo','Célula animal'],['Azul central','Núcleo'],['Amarelo','Mitocôndrias']],answers:['Complexo golgiense','Mitocôndria','Ribossomo'],correct:1,explanation:'A mitocôndria realiza etapas da respiração celular, incluindo a fosforilação oxidativa, responsável pela maior parte do ATP nessas condições.',hint:'Procure a organela relacionada à respiração celular.',points:0.3}
};
export const initialRequests = [{id:'r1',studentId:'a1',subject:'Matemática',activity:'Simulado preparatório',points:0.5,status:'Aprovado',term:'3º bimestre',date:'2026-09-07',evidence:'Participação no simulado conferida pela coordenação.',reviewer:'Coordenação (demo)'},{id:'r2',studentId:'a1',subject:'Química',activity:'Gincana de ciências',points:0.3,status:'Em análise',term:'3º bimestre',date:'2026-09-08',evidence:'Participação na equipe da gincana de ciências.'},{id:'r3',studentId:'a2',subject:'Redação',activity:'Reflexão sobre carreiras',points:0.2,status:'Em análise',term:'3º bimestre',date:'2026-09-08',evidence:'Relato da atividade e planejamento de estudos.'}];
export function initialState(){return {events:initialEvents,requests:initialRequests,attempts:[],completions:{},attendance:[],audit:[],term:'3º bimestre',limit:1,points:0.3};}
export const fmt = n => Number(n).toLocaleString('pt-BR',{maximumFractionDigits:2});
export const dateLabel = s => new Date(s+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'});
