import React,{useEffect} from 'react';
import {X,Info,Users,Bell,Check,Plus,PaperPlane,GraduationCap,ArrowCounterClockwise,BookOpen,ArrowRight} from '@phosphor-icons/react';
import {students,labs,fmt,dateLabel} from './data';
export function Dialog({modal,setModal,data,setData,student,studentId,lab,current,role,notify,audit,goto,onReset}){
 const close=()=>setModal(null);
 useEffect(()=>{const old=document.activeElement;const h=e=>{if(e.key==='Escape')close();};document.addEventListener('keydown',h);document.querySelector('.modal button')?.focus();return()=>{document.removeEventListener('keydown',h);old?.focus();};},[]);
 function requestPoints(e){e.preventDefault();const f=new FormData(e.currentTarget),source=modal.source||lab,idSource=modal.event?'event:'+modal.event.id:'lab:'+source;
  if(!modal.event?.released||!(modal.event.points>0)){notify('A coordenação precisa liberar esta atividade para resgate.');return;}
  if(data.requests.some(r=>r.studentId===studentId&&r.source===idSource&&r.term===data.term&&r.status!=='Devolvido')){notify('Esta atividade já tem uma solicitação neste bimestre.');return;}
  const file=f.get('file'),activity=f.get('activity'),req={id:crypto.randomUUID(),studentId,activity,subject:f.get('subject'),points:modal.event?modal.event.points:data.points,status:'Em análise',term:data.term,date:new Date().toLocaleDateString('en-CA'),evidence:f.get('evidence'),fileName:file?.name||'',source:idSource};setData(d=>({...d,requests:[...d.requests,req],audit:[audit('Solicitação enviada: '+activity+' · '+student.name),...d.audit]}));close();notify('Solicitação enviada à coordenação. A nota ainda não foi alterada.');
 }
 function publish(e){e.preventDefault();const f=new FormData(e.currentTarget),item={id:crypto.randomUUID(),title:f.get('title'),type:f.get('type'),date:f.get('date'),time:f.get('time'),place:f.get('place'),audience:f.get('audience'),description:f.get('description'),subject:f.get('subject'),points:Number(f.get('points')),released:f.get('released')==='on'};setData(d=>({...d,events:[...d.events,item],audit:[audit('Evento publicado: '+item.title),...d.audit]}));close();notify('Evento publicado para '+item.audience+'.');}
 const title=({points:'Resgatar pontos extras',eventForm:'Publicar evento',event:modal.event?.title,about:'Uma nova jornada para o Externato',rules:'Regras demonstrativas de pontuação',return:'Devolver para ajuste',requestDetail:'Detalhes da solicitação',study:'Estação de estudo',reset:'Reiniciar demonstração'})[modal.type];
 return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><section className="modal" role="dialog" aria-modal="true" aria-label={title} onKeyDown={e=>{if(e.key==='Tab'){const els=[...e.currentTarget.querySelectorAll('button,input,select,textarea,[tabindex="0"]')].filter(x=>!x.disabled),first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}><header><h2>{title}</h2><button className="icon-btn" aria-label="Fechar" title="Fechar" onClick={close}><X size={22}/></button></header>
 {modal.type==='points'&&<form onSubmit={requestPoints}><p>A coordenação confere a atividade antes de aprovar os pontos. Limite atual: {fmt(data.limit)} ponto por disciplina e bimestre.</p><label>Atividade<input name="activity" readOnly value={modal.event?.title||labs[modal.source].label}/></label><label>Disciplina<input name="subject" readOnly value={modal.event?.subject||labs[modal.source].subject}/></label><div className="notice"><GraduationCap/> Solicitação de {fmt(modal.event?.points??data.points)} ponto · {data.term}</div><label>Relato / comprovante da atividade<textarea required minLength="10" name="evidence" placeholder="Descreva o que realizou e o que aprendeu (mínimo de 10 caracteres)."/></label><label>Arquivo de apoio (opcional)<input name="file" type="file" accept=".pdf,.png,.jpg,.jpeg,.txt"/></label><small>Nesta prévia, apenas o nome do arquivo é registrado. O conteúdo não é enviado nem armazenado.</small><button className="primary" type="submit"><PaperPlane/> Enviar para análise</button></form>}
 {modal.type==='eventForm'&&role==='Coordenação'&&<form onSubmit={publish}><label>Título<input name="title" required maxLength="90" placeholder="Ex.: Feira de ciências"/></label><div className="form-row"><label>Tipo<select name="type">{['Prova','Simulado','Palestra','Gincana','Passeio','Evento'].map(t=><option key={t}>{t}</option>)}</select></label><label>Público<select name="audience"><option>Todos</option>{students.map(s=><option key={s.id}>{s.grade} {s.group}</option>)}</select></label></div><div className="form-row"><label>Data<input name="date" type="date" required defaultValue="2026-09-30"/></label><label>Horário<input name="time" type="time" required defaultValue="09:00"/></label></div><label>Local<input name="place" required placeholder="Auditório do colégio"/></label><label>Descrição<textarea name="description" required placeholder="Orientações para os alunos"/></label><div className="form-row"><label>Disciplina<select name="subject">{['Redação','Língua Portuguesa','Matemática','Química','Física','Biologia','História','Geografia','Inglês'].map(t=><option key={t}>{t}</option>)}</select></label><label>Pontos solicitáveis<input name="points" type="number" min="0" max={data.limit} step="0.1" defaultValue="0" required/></label></div><small>0 significa que o evento não concede pontos extras. Interesse não comprova presença.</small><label className="check-label"><input type="checkbox" name="released"/> Liberar resgate de pontos agora</label><button type="submit" className="primary"><Plus/> Publicar na agenda</button></form>}
 {modal.type==='event'&&<div className="event-detail"><span className="status">{modal.event.type}</span><h3>{dateLabel(modal.event.date)} · {modal.event.time}</h3><p>{modal.event.place}</p><p>{modal.event.description}</p><div className="notice"><Users/> Público: {modal.event.audience}</div>{role==='Aluno'&&<><button className="primary" onClick={()=>{const key=studentId+':'+modal.event.id;setData(d=>({...d,attendance:d.attendance.includes(key)?d.attendance.filter(x=>x!==key):[...d.attendance,key]}));notify('Seu interesse no evento foi atualizado.');}}>{data.attendance.includes(studentId+':'+modal.event.id)?<Check/>:<Bell/>}{data.attendance.includes(studentId+':'+modal.event.id)?'Retirar interesse':'Tenho interesse'}</button><small>Registro demonstrativo de interesse. Não é confirmação de presença nem notificação do Windows.</small>{modal.event.points>0&&modal.event.released&&<button className="secondary" onClick={()=>setModal({type:'points',event:modal.event})}>Resgatar · {fmt(modal.event.points)} ponto</button>}</>}</div>}
 {modal.type==='event'&&role==='Coordenação'&&modal.event.points>0&&<button className="primary" onClick={()=>{const released=!modal.event.released;setData(d=>({...d,events:d.events.map(e=>e.id===modal.event.id?{...e,released}:e),audit:[audit((released?'Resgate liberado: ':'Resgate pausado: ')+modal.event.title),...d.audit]}));setModal({...modal,event:{...modal.event,released}});notify(released?'Resgate liberado para os alunos.':'Novos resgates pausados.');}}>{modal.event.released?'Pausar resgate de pontos':'Liberar resgate de pontos'}</button>}
 {modal.type==='return'&&role==='Coordenação'&&<form onSubmit={e=>{e.preventDefault();const reason=new FormData(e.currentTarget).get('reason');setData(d=>({...d,requests:d.requests.map(r=>r.id===modal.request.id?{...r,status:'Devolvido',reason,reviewer:'Coordenação (demo)'}:r),audit:[audit('Solicitação devolvida: '+modal.request.activity),...d.audit]}));close();notify('Solicitação devolvida com orientação ao aluno.');}}><p>{modal.request.activity}</p><label>Orientação para o aluno<textarea name="reason" required minLength="5" placeholder="Explique o que precisa ser ajustado."/></label><button className="primary">Devolver solicitação</button></form>}
 {modal.type==='requestDetail'&&<div className="detail"><span className="status">{modal.request.status}</span><h3>{modal.request.activity}</h3><p>{students.find(s=>s.id===modal.request.studentId).name} · {modal.request.subject}</p><p>{modal.request.evidence}</p>{modal.request.fileName&&<p>Arquivo indicado: {modal.request.fileName} (conteúdo não armazenado)</p>}<div className="notice">{fmt(modal.request.points)} ponto · {modal.request.term}</div>{modal.request.reason&&<p><strong>Orientação:</strong> {modal.request.reason}</p>}{modal.request.reviewer&&<small>Responsável: {modal.request.reviewer}</small>}</div>}
 {modal.type==='rules'&&role==='Coordenação'&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),limit=+f.get('limit'),totals={};data.requests.filter(r=>r.status==='Aprovado').forEach(r=>{const k=r.studentId+r.subject+r.term;totals[k]=(totals[k]||0)+r.points;});if(Object.values(totals).some(n=>n>limit)){notify('O limite deve comportar os valores já aprovados.');return;}setData(d=>({...d,limit,term:f.get('term'),audit:[audit('Regras demonstrativas atualizadas'),...d.audit]}));close();notify('Regras atualizadas para novas solicitações.');}}><p>Valores e vinculações de eventos a disciplinas são exemplos demonstrativos. A grade e as regras finais serão cadastradas pela coordenação.</p><label>Bimestre<select name="term" defaultValue={data.term}>{[1,2,3,4].map(n=><option key={n}>{n}º bimestre</option>)}</select></label><label>Limite por disciplina e bimestre<input type="number" name="limit" min="0.1" max="10" step="0.1" defaultValue={data.limit} required/></label><p>O valor de cada resgate é definido no evento ou simulado. Quizzes concedem apenas XP.</p><button className="primary">Salvar regras</button></form>}
 {modal.type==='study'&&<div className="study"><span className="eyebrow blue">{current.subject}</span><h3>{current.label}</h3><p>{current.explanation}</p><div className="notice"><BookOpen/>{current.hint}</div><h3>Como estudar esta missão</h3><ol><li>Leia a explicação e identifique os dados.</li><li>Explore o modelo 3D e teste outra perspectiva.</li><li>Resolva a questão e revise a justificativa.</li></ol><small>O Externato utiliza o Sistema de Ensino Poliedro. Estas questões são exemplos originais da prévia; não reproduzem apostilas nem integram a plataforma Poliedro.</small><button className="primary" onClick={()=>{close();goto('lab');}}>Ir para o laboratório <ArrowRight/></button></div>}
 {modal.type==='about'&&<div className="about"><h3>Estudo que envolve. Gestão que acompanha.</h3><p>Uma prévia comercial para todas as turmas do Ensino Médio do Externato, preparada para Windows. O colégio utiliza o Sistema de Ensino Poliedro; esta prévia é independente, com conteúdo próprio e sem integração ao sistema.</p><ul><li>4 experiências de estudo com modelos 3D.</li><li>Missões, conquistas, EVI e estação de foco.</li><li>Agenda publicada pela coordenação.</li><li>Solicitação, aprovação e exportação de pontos.</li></ul><div className="notice"><Info/> Dados fictícios armazenados somente neste navegador. A troca de perfil simula permissões; não é autenticação.</div><p>Não há envio real de arquivos, integração com boletim, mensagens ou notificações externas. As planilhas são de demonstração.</p><button className="secondary" onClick={()=>setModal({type:'reset'})}><ArrowCounterClockwise/> Reiniciar dados da demonstração</button></div>}
 {modal.type==='reset'&&<div><h3>Reiniciar a demonstração?</h3><p>Isso remove apenas os registros fictícios criados neste navegador e restaura os exemplos iniciais.</p><div className="button-group"><button className="secondary" onClick={close}>Cancelar</button><button className="primary" onClick={onReset}>Reiniciar</button></div></div>}
 </section></div>;
}

