// Conteúdo original da prévia. Séries e turmas são uma distribuição demonstrativa,
// sem reprodução de questões ou afirmação de alinhamento à sequência do Poliedro.
export const subjectGuide = [
  ['Matemática', 'Alta', 'Sólidos, seções e volumes', 'Funções, estatística e probabilidade: gráficos e exercícios.'],
  ['Física', 'Alta', 'Trajetórias, ondas e vetores', 'Cálculos e circuitos simples: esquemas e gráficos.'],
  ['Química', 'Alta', 'Geometria molecular e estruturas', 'Estequiometria, soluções e equilíbrio: tabelas e exercícios.'],
  ['Biologia', 'Alta', 'Células, DNA e anatomia', 'Ecologia e hereditariedade: diagramas e problemas.'],
  ['Geografia', 'Alta', 'Globo, relevo e estrutura terrestre', 'Geopolítica e população: mapas, textos e indicadores.'],
  ['História', 'Pontual', 'Arquitetura e objetos de cultura material', 'Processos históricos: fontes, mapas e linhas do tempo.'],
  ['Língua Portuguesa', 'Baixa', 'O 3D não é necessário nos conteúdos desta amostra', 'Interpretação, sintaxe e coesão: textos anotados e exercícios.'],
  ['Literatura', 'Baixa', 'O 3D não é necessário nos conteúdos desta amostra', 'Obras, escolas literárias e contexto: leitura e comparação.'],
  ['Redação', 'Baixa', 'O 3D não é necessário nos conteúdos desta amostra', 'Tese, argumentação e intervenção: roteiros de escrita.'],
  ['Inglês', 'Baixa', 'O 3D não é necessário nos conteúdos desta amostra', 'Leitura e gramática: flashcards e exercícios contextualizados.'],
  ['Filosofia', 'Baixa', 'O 3D não é necessário nos conteúdos desta amostra', 'Conceitos e argumentos: comparação e debate orientado.'],
  ['Sociologia', 'Baixa', 'O 3D não é necessário nos conteúdos desta amostra', 'Instituições e sociedade: casos, textos e indicadores.'],
  ['Arte', 'Pontual', 'Escultura, volume e perspectiva', 'Movimentos e leitura de imagem: comparação de obras.'],
  ['Educação Física', 'Pontual', 'Biomecânica e movimentos articulares', 'Regras, saúde e cultura corporal: esquemas e discussão.'],
].map(([subject, priority, use, alternative]) => ({subject, priority, use, alternative}));
export const subjects = subjectGuide.map(s => s.subject);
export const classrooms = [1,2,3].flatMap(grade => ['A','B'].map(group => `${grade}º ${group}`));

// [série, conteúdo, [pergunta, alternativas, índice correto, explicação]...]
const bank = {
  'Matemática': [
    [1,'Funções afins',['Se f(x) = 2x + 3, quanto vale f(4)?',['8','11','14'],1,'Substituindo x por 4: 2 × 4 + 3 = 11.'],['Na função f(x) = −3x + 2, qual é a taxa de variação?',['2','3','−3'],2,'O coeficiente de x é a taxa de variação. Cada unidade em x reduz f(x) em 3.']],
    [2,'Geometria espacial',['Um prisma tem área da base de 12 cm² e altura de 5 cm. Qual é seu volume?',['60 cm³','30 cm³','17 cm³'],0,'V = área da base × altura = 12 × 5 = 60 cm³.'],['Um cone e um cilindro têm a mesma base e altura. O volume do cone é…',['igual ao do cilindro','um terço do volume do cilindro','o triplo do volume do cilindro'],1,'Para o cone, V = Ab × h ÷ 3; para o cilindro, V = Ab × h.']],
    [3,'Probabilidade',['Um dado equilibrado é lançado. Qual a probabilidade de sair número par?',['1/6','1/3','1/2'],2,'Há três resultados pares entre seis resultados possíveis.'],['Dois lançamentos independentes de uma moeda equilibrada dão duas caras com probabilidade…',['1/4','1/2','3/4'],0,'Multiplique as probabilidades independentes: 1/2 × 1/2 = 1/4.']],
  ],
  'Física': [
    [1,'Cinemática',['Um móvel percorre 120 m em 6 s em linha reta, sem retorno. Sua velocidade média em módulo é…',['720 m/s','20 m/s','126 m/s'],1,'Divida o deslocamento pelo intervalo de tempo: 120 ÷ 6 = 20 m/s.'],['No lançamento oblíquo ideal, o movimento horizontal tem…',['aceleração constante de 10 m/s²','velocidade nula','velocidade constante'],2,'Sem resistência do ar, a gravidade atua verticalmente e não altera a velocidade horizontal.']],
    [2,'Ondulatória',['Uma onda tem frequência de 5 Hz e comprimento de 2 m. Sua velocidade é…',['10 m/s','2,5 m/s','7 m/s'],0,'A relação é v = λf = 2 × 5 = 10 m/s.'],['Numa onda transversal, a oscilação é…',['paralela à propagação','perpendicular à propagação','sempre circular'],1,'Transversal significa oscilação perpendicular à direção de propagação.']],
    [3,'Eletricidade',['Um resistor de 6 Ω recebe 12 V. Qual é a corrente?',['72 A','0,5 A','2 A'],2,'Pela lei de Ohm, I = U/R = 12/6 = 2 A.'],['Dois resistores de 4 Ω em série equivalem a…',['8 Ω','2 Ω','16 Ω'],0,'Em série, somam-se as resistências: 4 + 4 = 8 Ω.']],
  ],
  'Química': [
    [1,'Ligações e geometria',['Qual é a geometria da molécula de CH₄?',['Linear','Tetraédrica','Angular'],1,'Quatro regiões ligantes, sem pares livres no carbono, se organizam tetraedricamente.'],['Uma ligação covalente envolve…',['compartilhamento de elétrons','fusão dos núcleos','apenas atração entre íons'],0,'Átomos compartilham pares de elétrons na ligação covalente.']],
    [2,'Soluções',['10 g de soluto formam 2 L de solução. Qual é a concentração comum?',['20 g/L','12 g/L','5 g/L'],2,'A concentração comum é massa do soluto dividida pelo volume da solução.'],['Ao diluir uma solução apenas adicionando água, a massa de soluto…',['aumenta','permanece igual','diminui'],1,'Na diluição sem perda ou reação, a quantidade de soluto permanece; o volume aumenta.']],
    [3,'Química orgânica',['Qual grupo funcional caracteriza os álcoois?',['Hidroxila ligada a carbono saturado','Carboxila','Carbonila entre carbonos'],0,'Nos álcoois, o grupo −OH está ligado a carbono saturado.'],['Qual é a fórmula molecular do etano?',['C₂H₄','C₂H₆','CH₄'],1,'Alcanos acíclicos seguem CnH2n+2. Para n = 2, resulta C₂H₆.']],
  ],
  'Biologia': [
    [1,'Citologia',['Qual organela realiza a maior parte da produção de ATP na respiração aeróbia eucariótica?',['Ribossomo','Complexo golgiense','Mitocôndria'],2,'A fosforilação oxidativa ocorre na membrana interna da mitocôndria.'],['A membrana plasmática é descrita pelo modelo…',['do mosaico fluido','da dupla hélice','da chave-fechadura'],0,'Uma bicamada lipídica fluida contém proteínas e outros componentes associados.']],
    [2,'DNA e genética',['No DNA, a adenina normalmente se emparelha com…',['Guanina','Timina','Citosina'],1,'As bases complementares são A–T e C–G.'],['Na replicação semiconservativa, cada molécula nova contém…',['duas fitas novas','duas fitas antigas','uma fita antiga e uma nova'],2,'Cada fita original orienta a síntese de uma fita complementar.']],
    [3,'Ecologia',['Qual grupo introduz energia em uma cadeia alimentar por fotossíntese?',['Produtores','Decompositores','Consumidores secundários'],0,'Produtores fotossintetizantes convertem energia luminosa em energia química.'],['Ao longo dos níveis tróficos, a energia disponível tende a…',['aumentar','diminuir','ficar constante'],1,'Parte da energia é dissipada como calor nos processos metabólicos de cada nível.']],
  ],
  'Geografia': [
    [1,'Coordenadas geográficas',['A latitude é medida a partir de qual referência?',['Meridiano de Greenwich','Trópico de Câncer','Linha do Equador'],2,'Latitude é a distância angular em relação ao Equador, de 0° a 90° N ou S.'],['A longitude varia de…',['0° a 180° a leste ou oeste','0° a 90° a norte ou sul','0° a 360° a norte'],0,'O meridiano de Greenwich é a referência para longitudes leste e oeste.']],
    [2,'Urbanização',['Urbanização é o aumento da…',['área rural apenas','participação da população urbana no total','produção agrícola apenas'],1,'O processo se refere ao crescimento relativo da população que vive em áreas urbanas.'],['Conurbação ocorre quando…',['uma cidade perde população','duas cidades mudam de país','manchas urbanas de cidades vizinhas se unem'],2,'É a continuidade física entre áreas urbanizadas antes separadas.']],
    [3,'Globalização',['As cadeias globais de produção se caracterizam pela…',['distribuição de etapas produtivas entre países','ausência de comércio internacional','produção de tudo em um único lugar'],0,'Empresas podem distribuir etapas entre diferentes territórios conectados por redes logísticas.'],['A globalização elimina todas as desigualdades regionais?',['Sim, automaticamente','Não; seus efeitos são desiguais','Sim, porque elimina fronteiras'],1,'Os territórios participam de maneira desigual dos fluxos de capital, informação e mercadorias.']],
  ],
  'História': [
    [1,'Fontes históricas',['Qual pode ser uma fonte histórica?',['Somente um documento oficial','Somente um texto escrito','Um objeto, relato ou documento contextualizado'],2,'Vestígios materiais, orais e escritos podem ser analisados como fontes.'],['Ao interpretar uma fonte, é essencial considerar…',['autoria, contexto e finalidade','apenas sua idade','apenas se confirma nossa opinião'],0,'A análise crítica relaciona a produção da fonte às condições e interesses de seu tempo.']],
    [2,'Revolução Industrial',['Uma transformação ligada à Revolução Industrial foi…',['o fim de todas as cidades','a expansão do sistema fabril','a eliminação do trabalho assalariado'],1,'A mecanização e a concentração de trabalhadores nas fábricas alteraram produção e relações sociais.'],['O pioneirismo britânico relaciona-se a…',['um fator isolado e universal','ausência de mercados','capitais, recursos, mercados e mudanças agrárias'],2,'Foi um processo com múltiplas condições econômicas, sociais e políticas.']],
    [3,'República e cidadania',['Cidadania política inclui…',['participação e direitos políticos','somente consumo','somente pagamento de impostos'],0,'Votar, organizar-se e participar da vida pública são dimensões da cidadania política.'],['A Constituição brasileira de 1988 está associada à…',['instauração da monarquia','redemocratização e ampliação de direitos','abolição da escravidão'],1,'Foi elaborada no contexto de redemocratização e ampliou garantias civis, políticas e sociais.']],
  ],
  'Língua Portuguesa': [
    [1,'Leitura e inferência',['Inferir uma informação significa…',['copiar uma frase','deduzir algo a partir de pistas do texto','ignorar o contexto'],1,'A inferência combina pistas textuais e conhecimentos pertinentes, sem inventar evidências.'],['A finalidade principal de um texto instrucional é…',['narrar uma ficção','defender qualquer tese','orientar a realização de uma ação'],2,'Receitas e manuais organizam orientações para realizar uma atividade.']],
    [2,'Sintaxe',['Em “Os estudantes revisaram a matéria”, o sujeito é…',['Os estudantes','a matéria','revisaram'],0,'O verbo concorda com o núcleo estudantes, parte do sujeito.'],['Em “A turma precisa de revisão”, “de revisão” é…',['objeto direto','objeto indireto','sujeito'],1,'Precisar, nesse sentido, exige a preposição de para introduzir seu complemento.']],
    [3,'Coesão textual',['Qual conectivo expressa oposição?',['Portanto','Porque','Entretanto'],2,'Entretanto introduz contraste em relação à ideia anterior.'],['Em “Ana leu o livro e o recomendou”, o pronome “o” retoma…',['o livro','Ana','o ato de ler'],0,'A retomada evita repetição e estabelece coesão referencial.']],
  ],
  'Literatura': [
    [1,'Linguagem literária',['Metáfora envolve…',['apenas descrição literal','aproximação de sentidos por semelhança','somente exagero numérico'],1,'A metáfora transfere sentidos com base numa relação de semelhança.'],['O eu lírico é necessariamente o autor?',['Sim, sempre','Sim, se o poema usa eu','Não; é a voz construída no poema'],2,'A voz poética é uma construção textual e não deve ser automaticamente confundida com o autor.']],
    [2,'Realismo',['Uma tendência do Realismo brasileiro é…',['análise crítica de relações sociais','idealização constante do herói','recusa de conflitos psicológicos'],0,'Obras realistas frequentemente problematizam instituições e comportamentos sociais.'],['Machado de Assis é autor de…',['Iracema','Memórias Póstumas de Brás Cubas','Os Lusíadas'],1,'O romance de 1881 usa um narrador defunto e ironia na análise da sociedade.']],
    [3,'Modernismo',['A Semana de Arte Moderna de 1922 ocorreu em…',['Recife','Rio de Janeiro','São Paulo'],2,'O evento aconteceu no Teatro Municipal de São Paulo.'],['Uma proposta modernista foi…',['experimentação estética e revisão de convenções','copiar sempre os modelos clássicos','proibir a linguagem cotidiana'],0,'Os modernismos valorizaram experimentação e novas relações com a cultura brasileira.']],
  ],
  'Redação': [
    [1,'Tese e recorte',['Em um texto argumentativo, a tese é…',['a cópia do tema','a posição defendida pelo autor','uma lista de referências'],1,'A tese delimita o posicionamento que os argumentos devem sustentar.'],['Um bom recorte temático ajuda a…',['fugir do tema','repetir a proposta','delimitar o problema discutido'],2,'Delimitar o problema dá foco à argumentação.']],
    [2,'Argumentação',['Um argumento consistente deve…',['apoiar a tese com razões e evidências pertinentes','apenas repetir a tese','depender só de exclamações'],0,'Explicações e evidências precisam estabelecer uma relação lógica com o ponto defendido.'],['O repertório contribui para o texto quando…',['é famoso, mesmo sem relação','é pertinente e articulado ao argumento','substitui toda a análise'],1,'A referência precisa ser explicada e relacionada ao raciocínio desenvolvido.']],
    [3,'Revisão do texto',['Na revisão, qual atitude melhora a clareza?',['Alongar todas as frases','Eliminar todos os conectivos','Verificar encadeamento e referências ambíguas'],2,'A clareza depende de relações explícitas entre ideias e referências compreensíveis.'],['Uma conclusão coerente deve…',['retomar o raciocínio e fechar a discussão','introduzir qualquer assunto novo','contradizer a tese sem explicar'],0,'O fechamento precisa decorrer do percurso argumentativo desenvolvido.']],
  ],
  'Inglês': [
    [1,'Estratégias de leitura',['Scanning é uma estratégia para…',['traduzir todas as palavras','localizar uma informação específica','decorar o texto inteiro'],1,'Scanning busca rapidamente um dado, nome ou informação específica.'],['Em “She studies every day”, a expressão indica…',['ação encerrada no passado','hipótese impossível','hábito ou rotina'],2,'O simple present é usado para hábitos; every day reforça essa leitura.']],
    [2,'Passado e contexto',['Qual frase está no simple past?',['They visited the museum.','They visit the museum.','They will visit the museum.'],0,'Visited marca o passado do verbo regular visit.'],['Em “I was reading when she arrived”, a leitura era…',['posterior a todos os fatos','uma ação em andamento no passado','uma ordem'],1,'Past continuous apresenta uma ação em curso quando outra acontece.']],
    [3,'Conectivos e argumentação',['Qual conectivo pode indicar consequência?',['Although','However','Therefore'],2,'Therefore significa portanto, introduzindo uma conclusão ou consequência.'],['“Although it rained, we went out” expressa…',['concessão','causa exclusiva','ordem cronológica'],0,'Although introduz uma circunstância que não impediu o fato principal.']],
  ],
  'Filosofia': [
    [1,'Pergunta filosófica',['A reflexão filosófica busca…',['aceitar opiniões sem exame','examinar fundamentos e argumentos','evitar perguntas'],1,'A investigação filosófica questiona pressupostos e avalia justificativas.'],['Um argumento é formado por…',['apenas uma exclamação','qualquer lista de palavras','premissas que apoiam uma conclusão'],2,'Premissas oferecem razões para aceitar uma conclusão.']],
    [2,'Ética',['A ética estuda principalmente…',['fundamentos e critérios da ação moral','apenas fenômenos climáticos','somente regras gramaticais'],0,'A ética investiga como justificar avaliações e escolhas morais.'],['Um dilema moral pode envolver…',['ausência de qualquer escolha','conflito entre valores ou deveres','somente erro de cálculo'],1,'Dilemas podem exigir ponderação entre deveres ou valores que entram em tensão.']],
    [3,'Conhecimento',['O empirismo atribui papel central à…',['herança genética de ideias','autoridade sem exame','experiência na formação do conhecimento'],2,'Tradições empiristas enfatizam a experiência como fonte de conhecimento.'],['Avaliar criticamente uma afirmação exige…',['examinar razões, evidências e limites','aceitá-la por ser popular','rejeitá-la por ser nova'],0,'A avaliação crítica analisa a sustentação da afirmação e possíveis objeções.']],
  ],
  'Sociologia': [
    [1,'Socialização',['Socialização é o processo de…',['formação apenas biológica','aprendizagem de normas e práticas sociais','eliminação das diferenças culturais'],1,'As pessoas aprendem e negociam modos de participação na vida social.'],['Qual pode ser um agente de socialização?',['Somente o Estado','Somente a escola','Família, escola e grupos de convivência'],2,'Diversos espaços e grupos participam da socialização ao longo da vida.']],
    [2,'Cultura e diversidade',['Etnocentrismo consiste em…',['julgar outras culturas pelo padrão da própria','compreender todas as culturas em seu contexto','ausência de referências culturais'],0,'O etnocentrismo toma a cultura de referência como medida superior ou universal.'],['A diversidade cultural mostra que…',['há um único modo legítimo de viver','existem diferentes práticas e significados sociais','cultura é apenas herança biológica'],1,'Práticas e significados são construídos historicamente e variam entre grupos.']],
    [3,'Trabalho e desigualdade',['Desigualdade social envolve…',['apenas diferenças de gosto','somente diferenças de altura','acesso desigual a recursos e oportunidades'],2,'Renda, educação, poder e serviços são dimensões possíveis de desigualdade.'],['Mobilidade social é…',['mudança de posição na estrutura social','deslocamento diário até a escola','qualquer viagem internacional'],0,'O conceito trata de mudanças de posição entre estratos ou grupos sociais.']],
  ],
  'Arte': [
    [1,'Elementos visuais',['Qual conjunto reúne elementos da linguagem visual?',['Sujeito, verbo e predicado','Linha, cor, forma e textura','Corrente, tensão e resistência'],1,'Esses elementos participam da construção e percepção das imagens.'],['Uma escultura se distingue de uma imagem plana por explorar…',['apenas a cor','somente a escrita','volume e espaço tridimensional'],2,'Esculturas podem ser observadas de diferentes ângulos no espaço.']],
    [2,'Perspectiva',['Na perspectiva linear, linhas paralelas em profundidade parecem…',['convergir para pontos de fuga','ficar sempre verticais','desaparecer na origem'],0,'Pontos de fuga ajudam a construir a sensação de profundidade numa superfície plana.'],['O claro-escuro pode sugerir…',['apenas movimento literal','volume e iluminação','ausência de forma'],1,'Contrastes de luz e sombra contribuem para a percepção de volume.']],
    [3,'Arte contemporânea',['Uma instalação artística pode…',['existir apenas em uma tela','dispensar qualquer relação espacial','articular objetos, espaço e experiência do público'],2,'Instalações usam o espaço e podem envolver a presença ou participação do observador.'],['Ler uma obra em seu contexto significa…',['relacionar escolhas artísticas a condições de produção','ignorar o período','procurar uma única interpretação obrigatória'],0,'O contexto amplia a compreensão sem reduzir a obra a uma só interpretação.']],
  ],
  'Educação Física': [
    [1,'Cultura corporal',['A cultura corporal inclui…',['apenas esporte profissional','jogos, danças, lutas e outras práticas','somente exercícios individuais'],1,'Práticas corporais têm significados sociais e históricos diversos.'],['Cooperação em um jogo envolve…',['impedir a participação dos colegas','ignorar regras combinadas','articular ações para objetivos compartilhados'],2,'Cooperar envolve comunicação e responsabilidade coletiva.']],
    [2,'Movimento e articulações',['A flexão do cotovelo normalmente…',['diminui o ângulo entre braço e antebraço','aumenta indefinidamente esse ângulo','gira apenas o punho'],0,'Flexão e extensão descrevem mudanças no ângulo entre segmentos corporais.'],['Para comparar um gesto motor, um modelo 3D ajuda a observar…',['somente a cor do uniforme','a posição dos segmentos em diferentes vistas','a pontuação de um campeonato'],1,'A rotação do modelo evidencia relações espaciais que uma única imagem pode esconder.']],
    [3,'Esporte e sociedade',['Fair play está relacionado a…',['vencer a qualquer custo','desrespeitar acordos','respeito às regras e aos participantes'],2,'O jogo limpo envolve conduta ética e respeito durante a prática esportiva.'],['A inclusão nas práticas corporais requer…',['considerar diferentes condições de participação','exigir um único padrão corporal','excluir quem está aprendendo'],0,'Adaptações podem ampliar a participação e o acesso às experiências corporais.']],
  ],
};
export const topics = Object.entries(bank).flatMap(([subject, rows], si) => rows.map(([grade,title,...items], ti) => {
  const id = `topic-${si}-${ti}`;
  const questions = items.map(([prompt,options,correct,explanation], qi) => ({id:`${id}-q${qi}`,topicId:id,subject,grade,prompt,options,correct,explanation}));
  return {id,subject,grade,title,audiences:[`${grade}º A`,`${grade}º B`],questions,
    cards:questions.map(q=>({id:q.id,topicId:id,subject,front:q.prompt,back:q.options[q.correct],explanation:q.explanation}))};
}));
export function filterTopics({classroom,subject='Todas',topic='Todos'}, list=topics) {
  return list.filter(t=>t.audiences.includes(classroom)&&(subject==='Todas'||t.subject===subject)&&(topic==='Todos'||t.id===topic));
}
export function scoreAnswers(questions, answers) {
  const correct = questions.filter(q=>answers[q.id]===q.correct).length;
  return {correct,total:questions.length,percent:questions.length?Math.round(correct/questions.length*100):0};
}
export function scheduleReview(confidence, now=Date.now()) {
  const days = confidence==='known'?3:confidence==='partial'?1:0;
  return {confidence,nextReview:now+days*86400000};
}
export function dueCards(cards,reviews={},now=Date.now()) {
  return cards.filter(c=>!reviews[c.id]||reviews[c.id].nextReview<=now);
}
export const models = [
  {id:'geometry',subject:'Matemática',title:'Prisma triangular',content:'Geometria espacial',years:[2,3],objective:'Relacionar a área da base à altura do prisma.',parts:['2 bases triangulares','3 faces laterais','6 vértices'],steps:['Compare as duas bases triangulares usando a vista frontal.','Gire o prisma e conte as faces laterais.','Use Ab = 15 cm² e h = 10 cm para calcular V = 150 cm³.'],note:'Modelo proporcional às medidas do desafio. As medidas são dadas no roteiro.'},
  {id:'solids',subject:'Matemática',title:'Cone e cilindro',content:'Volumes de revolução',years:[2,3],objective:'Comparar sólidos com a mesma base e a mesma altura.',parts:['Cilindro: V = πr²h','Cone: V = πr²h/3','Bases de mesmo raio'],steps:['Observe os dois sólidos na vista frontal.','Compare os raios e as alturas iguais.','Discuta por que o volume do cone é um terço do volume do cilindro.'],note:'Comparação geométrica; o desenho não é uma demonstração por preenchimento.'},
  {id:'chemistry',subject:'Química',title:'Molécula de metano',content:'Geometria molecular',years:[1,3],objective:'Visualizar a distribuição espacial das quatro ligações do CH₄.',parts:['Carbono central','4 hidrogênios','Ligações C–H'],steps:['Localize o carbono e conte os hidrogênios.','Gire até perceber que os átomos não estão no mesmo plano.','Relacione o arranjo tetraédrico ao ângulo de aproximadamente 109,5°.'],note:'Representação de esferas e varetas; tamanhos e cores são convenções didáticas.'},
  {id:'physics',subject:'Física',title:'Lançamento oblíquo',content:'Cinemática',years:[1,3],objective:'Relacionar ângulo, trajetória e alcance no modelo ideal.',parts:['Projétil','Trajetória parabólica','Eixo horizontal'],steps:['Compare o alcance nos ângulos de 30° e 60°.','Ajuste para 45° e observe o alcance máximo.','Pause e separe mentalmente os movimentos horizontal e vertical.'],note:'v₀ = 20 m/s; g = 10 m/s²; sem ar; partida e chegada na mesma altura.'},
  {id:'wave',subject:'Física',title:'Onda transversal',content:'Ondulatória',years:[2,3],objective:'Distinguir oscilação de partículas e propagação da perturbação.',parts:['Linha azul: perfil da onda','Ponto amarelo: uma posição do meio','Direção horizontal de propagação'],steps:['Observe a onda e o ponto amarelo marcado.','Pause e localize uma crista e um vale.','Retome: o ponto oscila verticalmente enquanto o perfil se desloca.'],note:'Onda senoidal ideal. A animação é ilustrativa, sem escala de tempo física.'},
  {id:'biology',subject:'Biologia',title:'Célula animal',content:'Citologia',years:[1,3],objective:'Reconhecer núcleo, mitocôndrias e limite celular.',parts:['Membrana plasmática','Núcleo','Mitocôndrias'],steps:['Identifique o limite celular e o núcleo.','Clique em uma mitocôndria e discuta sua função.','Use a separação de componentes para localizar as estruturas.'],note:'Recorte esquemático com três estruturas. Não representa todas as organelas nem suas proporções.'},
  {id:'dna',subject:'Biologia',title:'Dupla hélice de DNA',content:'DNA e genética',years:[2,3],objective:'Identificar duas fitas e o emparelhamento complementar de bases.',parts:['Duas cadeias de açúcar e fosfato','Pares A–T','Pares C–G'],steps:['Siga uma das duas cadeias ao girar o modelo.','Clique nas bases e identifique A–T e C–G.','Discuta como cada fita pode orientar uma nova fita complementar.'],note:'Esquema de dupla hélice; não é um modelo atômico nem mostra ligações de hidrogênio individuais.'},
  {id:'globe',subject:'Geografia',title:'Globo e coordenadas',content:'Coordenadas geográficas',years:[1,3],objective:'Distinguir latitude de longitude e reconhecer suas referências.',parts:['Equador em amarelo','Meridiano de Greenwich em vermelho','Paralelos e meridianos'],steps:['Use a vista frontal para localizar o Equador.','Gire e compare paralelos com meridianos.','Identifique a referência de longitude e explique os hemisférios.'],note:'Globo geométrico sem continentes; foco na rede de coordenadas, sem escala cartográfica.'},
];
