import React,{useState,useEffect} from 'react';
import {House,Flag,Cube,CalendarDots,ChartBar,GraduationCap,ArrowRight,Check,CheckCircle,BookOpen,Flask,Trophy,Lightning,Download,Plus,X,Bell,Clock,Users,Gear,ArrowCounterClockwise,Info,Play,Pause,PaperPlane,MagnifyingGlass,ShieldCheck,Star} from '@phosphor-icons/react';
import * as XLSX from 'xlsx';
import {Scene} from './Scene';
import {students,initialState,labs,fmt,dateLabel} from './data';
import {Dialog} from './Dialog';
import {TeachingLab} from './TeachingLab';
import {StudyHub} from './StudyHub';

const KEY='externapp-demo-v2';
const icons={geometry:Cube,chemistry:Flask,physics:Lightning,biology:BookOpen};
const tabs=[['home','Início',House],['overview','Painel',ChartBar],['journey','Jornada',Flag],['study','Estudos',BookOpen],['lab','Laboratório 3D',Cube],['agenda','Agenda',CalendarDots],['results','Resultados',ChartBar]];
function load(){try{const d=JSON.parse(localStorage.getItem(KEY));if(d?.events&&d?.requests){const migrate=r=>({...r,subject:r.subject==='Projeto de Vida'?'Redação':r.subject==='Linguagens'?'Língua Portuguesa':r.subject});return {...d,events:d.events.map(migrate),requests:d.requests.map(migrate)};}return initialState();}catch{return initialState();}}
export function Empty({children}){return <div className="empty"><Info size={28}/><p>{children}</p></div>}
export function App(){
 const [data,setData]=useState(load),[tab,setTab]=useState('home'),[role,setRole]=useState('Aluno'),[studentId,setStudentId]=useState('a1'),[lab,setLab]=useState('geometry'),[selected,setSelected]=useState(null),[feedback,setFeedback]=useState(null),[angle,setAngle]=useState(45),[hint,setHint]=useState(false),[modal,setModal]=useState(null),[toast,setToast]=useState(''),[filter,setFilter]=useState('Todos'),[search,setSearch]=useState(''),[adminGroup,setAdminGroup]=useState('Todos'),[adminStatus,setAdminStatus]=useState('Todos'),[seconds,setSeconds]=useState(1500),[running,setRunning]=useState(false);
 const student=students.find(s=>s.id===studentId),current=labs[lab],done=data.completions[studentId]||[],attempts=data.attempts.filter(a=>a.studentId===studentId),requests=data.requests.filter(r=>r.studentId===studentId);
 const approved=requests.filter(r=>r.status==='Aprovado'&&r.term===data.term).reduce((s,r)=>s+r.points,0),pending=requests.filter(r=>r.status==='Em análise'&&r.term===data.term).reduce((s,r)=>s+r.points,0),progress=Math.round(done.length/4*100),xp=done.length*100,level=1+Math.floor(xp/200);
 const visibleEvents=data.events.filter(e=>e.audience==='Todos'||e.audience===`${student.grade} ${student.group}`).sort((a,b)=>a.date.localeCompare(b.date)),upcoming=visibleEvents.find(e=>e.date>=new Date().toLocaleDateString('en-CA'))||visibleEvents[0];
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(data));}catch{setToast('O navegador não conseguiu salvar a prévia. Mantenha a janela aberta.');}},[data]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);}},[toast]);
 useEffect(()=>{if(!running)return;const t=setInterval(()=>setSeconds(n=>{if(n<=1){setRunning(false);return 0;}return n-1;}),1000);return()=>clearInterval(t);},[running]);
 useEffect(()=>{setSelected(null);setFeedback(null);setHint(false);},[lab,studentId]);
 const notify=t=>setToast(t);
 const audit=text=>({id:crypto.randomUUID(),text,date:new Date().toLocaleString('pt-BR')});
 function goto(t){setTab(t);setFilter('Todos');setSearch('');}
 function checkAnswer(){if(selected===null){notify('Escolha uma resposta antes de conferir.');return;}const correct=selected===current.correct;setFeedback(correct?'correct':'wrong');setData(d=>({...d,attempts:[...d.attempts,{id:crypto.randomUUID(),studentId,lab,subject:current.subject,correct,date:new Date().toISOString()}],completions:correct?{...d.completions,[studentId]:[...new Set([...(d.completions[studentId]||[]),lab])]}:d.completions}));if(correct)notify(done.includes(lab)?'Revisão concluída. Sua conquista já está registrada.':'Missão concluída! +100 XP de jornada.');}
 function review(r,status){if(status==='Devolvido'){setModal({type:'return',request:r});return;}const sum=data.requests.filter(x=>x.id!==r.id&&x.studentId===r.studentId&&x.subject===r.subject&&x.term===r.term&&x.status==='Aprovado').reduce((s,x)=>s+x.points,0);if(sum+r.points>data.limit+.00001){notify(`Limite de ${fmt(data.limit)} ponto por disciplina e bimestre excedido.`);return;}setData(d=>({...d,requests:d.requests.map(x=>x.id===r.id?{...x,status,reviewer:'Coordenação (demo)',reviewDate:new Date().toLocaleString('pt-BR')}:x),audit:[audit('Aprovado: '+r.activity+' · '+fmt(r.points)+' ponto'),...d.audit]}));notify('Pontos aprovados. Resultados e exportação atualizados.');}
 const filteredRequests=data.requests.filter(r=>{const s=students.find(s=>s.id===r.studentId);return (adminGroup==='Todos'||`${s.grade} ${s.group}`===adminGroup)&&(adminStatus==='Todos'||r.status===adminStatus)&&(!search||`${s.name} ${r.activity}`.toLowerCase().includes(search.toLowerCase()));});
 function exportResults(type){const list=role==='Aluno'?requests:filteredRequests,rows=list.map(r=>{const s=students.find(s=>s.id===r.studentId);return {'Aluno':s.name,'Matrícula demo':s.id,'Série':s.grade,'Turma':s.group,'Disciplina':r.subject,'Bimestre':r.term,'Atividade':r.activity,'Pontos solicitados':r.points,'Pontos aprovados':r.status==='Aprovado'?r.points:0,'Situação':r.status,'Comprovante':r.evidence,'Arquivo (nome apenas)':r.fileName||'','Responsável':r.reviewer||'','Data':r.date,'Observação':r.reason||''};});if(!rows.length){notify('Não há lançamentos para exportar com estes filtros.');return;}
  const sheet=XLSX.utils.json_to_sheet(rows);sheet['!cols']=Object.keys(rows[0]).map(k=>({wch:k==='Atividade'||k==='Comprovante'?36:23}));if(type==='xlsx'){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,sheet,'Pontos escolares');const results=data.attempts.filter(a=>role!=='Aluno'||a.studentId===studentId).filter(a=>role==='Aluno'||adminGroup==='Todos'||`${students.find(s=>s.id===a.studentId).grade} ${students.find(s=>s.id===a.studentId).group}`===adminGroup).map(a=>({'Aluno':students.find(s=>s.id===a.studentId).name,'Disciplina':a.subject,'Atividade':labs[a.lab].label,'Resultado':a.correct?'Correto':'Revisar','Data':new Date(a.date).toLocaleString('pt-BR')}));if(results.length)XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(results),'Tentativas');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{Aviso:'PRÉVIA COM DADOS FICTÍCIOS. Não é boletim oficial.',Regra:`Limite demonstrativo: ${data.limit} ponto por disciplina e bimestre. Apenas aprovados compõem o total.`}]),'Leia-me');XLSX.writeFile(wb,'ExternApp-resultados-demo.xlsx');}else{const safe=rows.map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>[k,typeof v==='string'&&/^[=+@\-]/.test(v)?"'"+v:v])));const csv='\uFEFF'+XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(safe),{FS:';'}),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='ExternApp-resultados-demo.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}notify('Planilha de demonstração exportada.');}

 function exportStudies(){
  const sessions=(data.studySessions||[]).filter(s=>role==='Coordenação'?(adminGroup==='Todos'||s.classroom===adminGroup):s.studentId===studentId);
  if(!sessions.length){notify('Conclua uma prática ou simulado na Central de estudos para exportar resultados.');return;}
  const rows=sessions.map(s=>{const who=students.find(p=>p.id===s.studentId);return {'Aluno':who?.name||s.studentId,'Turma do aluno':who?who.grade+' '+who.group:'','Turma do material':s.classroom,'Matérias':s.subjects.join(', '),'Ferramenta':s.mode==='exam'?'Simulado':'Questões','Acertos':s.correct,'Total de questões':s.total,'Percentual de acerto':s.percent,'Data':new Date(s.date).toLocaleString('pt-BR'),'Observação':'Treino demonstrativo; não concede pontos escolares.'};});
  const workbook=XLSX.utils.book_new(),sheet=XLSX.utils.json_to_sheet(rows);sheet['!cols']=Object.keys(rows[0]).map(()=>({wch:25}));XLSX.utils.book_append_sheet(workbook,sheet,'Estudos');XLSX.writeFile(workbook,'ExternApp-estudos-demo.xlsx');notify('Resultados de estudo exportados.');
 }
 function Stats(){return <><section className="panel progress-panel"><h3>Seu progresso <small>nesta prévia</small></h3><div className="progress-flex"><div className="ring"><ChartBar size={22}/><strong>{progress}%</strong><span>concluído</span></div><div className="subject-bars">{Object.entries(labs).map(([k,l])=><button onClick={()=>{setLab(k);goto('practice');}} key={k}><span>{l.subject}<b>{done.includes(k)?'100':'0'}%</b></span><progress value={done.includes(k)?100:0} max="100"/></button>)}</div></div></section><button className="panel academic" onClick={()=>goto('results')}><GraduationCap size={25}/><div><h3>Status acadêmico</h3><p>Pontos escolares · {data.term}</p><span className="green">{fmt(approved)} aprovado</span><span className="yellow"> · {fmt(pending)} em análise</span></div></button></>}
 function Laboratory({compact=false}){return <section className={'laboratory '+(compact?'compact':'')}><div className="lab-viewport"><div className="lab-heading"><span>Laboratório 3D <i>/</i> {current.subject}</span>{!compact&&<h2>{current.label}</h2>}<p><ArrowCounterClockwise size={18}/>{current.instruction}</p></div><Scene kind={lab} angle={angle}/>{lab==='physics'&&<label className="angle-control">Ângulo: {angle}° · alcance: {fmt(40*Math.sin(2*angle*Math.PI/180))} m<input aria-label="Ângulo de lançamento" type="range" min="15" max="75" value={angle} onChange={e=>setAngle(+e.target.value)}/></label>}<div className="lab-switch">{Object.entries(labs).map(([key,l])=><button key={key} title={l.label} aria-label={l.label} aria-pressed={key===lab} className={key===lab?'active':''} onClick={()=>setLab(key)}>{React.createElement(icons[key],{size:18})}</button>)}</div></div><div className="question"><span className="eyebrow">DESAFIO · {current.subject.toUpperCase()}</span><h3>{current.question}</h3><dl>{current.measurements.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><fieldset disabled={feedback!==null}><legend className="sr-only">Escolha sua resposta</legend>{current.answers.map((a,i)=><label key={a} className={'answer '+(selected===i?'selected':'')}><input type="radio" name="answer" checked={selected===i} onChange={()=>setSelected(i)}/><span>{a}</span>{selected===i&&<Check size={16}/>}</label>)}</fieldset>{feedback?<div className={'feedback '+feedback}><strong>{feedback==='correct'?'Você descobriu!':'Vamos revisar juntos?'}</strong><p>{current.explanation}</p><button className="text-btn" onClick={()=>{setFeedback(null);setSelected(null);}}>Praticar novamente</button>{feedback==='correct'&&<span className="xp-earned">Missão concluída · 100 XP de aprendizagem</span>}</div>:<><button className="primary" onClick={checkAnswer}>Conferir resposta <ArrowRight size={18}/></button><button className="hint" onClick={()=>setHint(!hint)}><Lightning size={15}/> Uma dica da EVI</button>{hint&&<p className="hint-text">{current.hint}</p>}</>}<small className="academic-note">Quizzes rendem XP e conquistas. Pontos escolares vêm de eventos e simulados liberados.</small></div></section>}
 function JourneyStrip(){return <section className="journey-strip" aria-label="Etapas de aprendizagem"><img src="/assets/journey.png" alt="Ilhas de revisão, prática, laboratório e conquista conectadas por um caminho luminoso"/><div>{['Revisão','Prática','Laboratório','Desafio'].map((name,i)=><button key={name} onClick={()=>{if(i===0)goto('study');else if(i===3)goto('journey');else goto('practice');}}><span>0{i+1}</span>{name}<ArrowRight size={17}/></button>)}</div></section>}
 function ResultTable({rows,admin=false}){return <div className="table-scroll"><table><thead><tr>{admin&&<th>Aluno / turma</th>}<th>Atividade</th><th>Disciplina</th><th>Solicitado</th><th>Aprovado</th><th>Situação</th><th>{admin?'Ações':'Detalhes'}</th></tr></thead><tbody>{rows.map(r=>{const s=students.find(s=>s.id===r.studentId);return <tr key={r.id}>{admin&&<td><strong>{s.name}</strong><small>{s.grade} ano {s.group}</small></td>}<td>{r.activity}<small>{r.term} · {dateLabel(r.date)}</small></td><td>{r.subject}</td><td>{fmt(r.points)}</td><td>{r.status==='Aprovado'?fmt(r.points):'—'}</td><td><span className={'status '+(r.status==='Aprovado'?'approved':r.status==='Devolvido'?'returned':'pending')}>{r.status}</span></td><td><div className="row-actions"><button title="Ver comprovante" aria-label={'Ver detalhes de '+r.activity} onClick={()=>setModal({type:'requestDetail',request:r})}><MagnifyingGlass size={17}/></button>{admin&&r.status==='Em análise'&&<><button className="approve" onClick={()=>review(r,'Aprovado')}>Aprovar</button><button onClick={()=>review(r,'Devolvido')}>Devolver</button></>}{!admin&&r.status==='Devolvido'&&r.source?.startsWith('event:')&&<button onClick={()=>setModal({type:'points',event:data.events.find(e=>'event:'+e.id===r.source)})}>Reenviar</button>}</div></td></tr>;})}</tbody></table>{!rows.length&&<Empty>Nenhum lançamento encontrado.</Empty>}</div>}
 const agendaList=(role==='Coordenação'?data.events:visibleEvents).filter(e=>(filter==='Todos'||e.type===filter)&&e.title.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>a.date.localeCompare(b.date));
 return <div className={`app page-${tab}`}><header className="topbar"><button className="brand" onClick={()=>goto('home')}><span className="brand-symbol"><img src="/assets/logo.png" alt="Colégio Externato"/></span><span>Extern<span className="yellow">App</span></span></button><nav aria-label="Navegação principal">{tabs.map(([key,label,Icon])=><button className={(tab===key?'active ':'')+(tab==='overview'&&key==='lab'?'lab-context':'')} aria-current={tab===key?'page':undefined} key={key} onClick={()=>goto(key)}><Icon size={21}/>{label}</button>)}</nav><div className="top-actions"><select aria-label="Perfil de demonstração" value={role} onChange={e=>{setRole(e.target.value);goto(e.target.value==='Coordenação'?'admin':e.target.value==='Professor'?'lab':'home');}}><option>Aluno</option><option>Professor</option><option>Coordenação</option></select><button className="avatar" aria-label="Sobre esta prévia" onClick={()=>setModal({type:'about'})}>{role==='Aluno'?student.name.split(' ').map(s=>s[0]).join(''):role==='Professor'?'PR':'CO'}</button></div></header><div className="demo-bar"><span><b className="yellow">● Prévia</b> · dados fictícios · salvos neste navegador</span><div>{role==='Aluno'&&<select aria-label="Aluno e turma de demonstração" value={studentId} onChange={e=>setStudentId(e.target.value)}>{students.map(s=><option key={s.id} value={s.id}>{s.name} · {s.grade} {s.group}</option>)}</select>}<span className="today"><CalendarDots size={16}/> {new Date().toLocaleDateString('pt-BR',{day:'numeric',month:'long',year:'numeric'})}</span><button aria-label="Informações da prévia" onClick={()=>setModal({type:'about'})}><Info size={18}/></button></div></div>
 <main>{role==='Professor'&&<div className="teacher-banner"><GraduationCap size={28}/><span>Espaço do professor<small>Escolha uma matéria e apresente um modelo para a turma.</small></span><button className="secondary" onClick={()=>goto('lab')}>Acervo 3D</button><button className="secondary" onClick={()=>goto('study')}>Materiais de estudo</button></div>}{role==='Coordenação'&&<div className="admin-banner"><ShieldCheck size={20}/><span>Ambiente da coordenação <small>Gestão demonstrativa · sem registros reais</small></span><button className={tab==='admin'?'primary small':'secondary small'} onClick={()=>goto('admin')}>Gerenciar pontos</button><button className="secondary small" onClick={()=>{goto('agenda');setModal({type:'eventForm'});}}><Plus/> Publicar evento</button><button className="icon-btn" aria-label="Regras de pontos" onClick={()=>setModal({type:'rules'})}><Gear size={22}/></button></div>}

 {tab==='home'&&<div className="evi-home"><section className="evi-hero"><div className="evi-hero-copy"><div className="evi-progress"><progress aria-label="Progresso da jornada" value={progress} max="100"/><span>Nível {level} · {xp} XP · {done.length}/4 missões</span></div><p className="evi-greeting">Olá, {student.name.split(' ')[0]}.</p><h1>O que vamos<br/><em>descobrir hoje?</em></h1><p className="evi-intro">Estude, explore e acompanhe sua jornada<br/>no ExternApp. A EVI vai com você.</p><div className="button-group"><button className="primary" onClick={()=>goto('lab')}>Explorar laboratório <ArrowRight/></button><button className="secondary" onClick={()=>goto('overview')}>Meu painel</button></div></div><div className="evi-hero-art"><img src="/assets/evi.png" alt="EVI, a arara azul exploradora do ExternApp"/><span className="evi-signature">EVI <small>Sua parceira de descobertas</small></span></div></section><div className="evi-shortcuts">{[['journey','Minha jornada','Missões, conquistas e foco',Flag],['study','Estudos','Flashcards, questões e simulados',BookOpen],['agenda','Agenda','Provas, encontros e experiências',CalendarDots]].map(([key,title,desc,Icon])=><button key={key} onClick={()=>goto(key)}><Icon size={28}/><ArrowRight size={23}/><h2>{title}</h2><p>{desc}</p></button>)}</div><div className="evi-home-foot"><span>Grandes descobertas começam com pequenos passos.</span><button onClick={()=>goto('rewards')}>Resgatar pontos de atividades <ArrowRight size={16}/></button></div></div>}
 {tab==='rewards'&&<><div className="page-heading"><div><span className="eyebrow yellow">PARTICIPOU? RESGATE.</span><h1>Seus pontos extras.</h1><p>Resgates de eventos e simulados. A coordenação valida sua participação antes de contabilizar a nota.</p></div><button className="secondary" onClick={()=>goto('results')}>Histórico de resgates <ArrowRight/></button></div><div className="events-grid">{visibleEvents.filter(e=>e.points>0).map(e=>{const req=requests.find(r=>r.source==='event:'+e.id&&r.term===data.term&&r.status!=='Devolvido');return <article className="panel event-card" key={e.id}><span className={'status '+(e.released?'approved':'pending')}>{req?req.status:e.released?'Resgate liberado':'Aguardando liberação'}</span><h2>{e.title}</h2><p>{e.type} · {dateLabel(e.date)}</p><strong className="reward-number">+{fmt(e.points)} ponto</strong><p>{e.subject} · {data.term}</p><button className={e.released&&!req?'primary':'secondary'} disabled={!e.released||!!req} onClick={()=>setModal({type:'points',event:e})}>{req?'Solicitação registrada':e.released?'Resgatar pontos':'Em breve'}</button>{!e.released&&<small>A coordenação ainda não liberou esta atividade.</small>}</article>})}</div><p className="muted">Quizzes e tempo de estudo não concedem pontos escolares.</p></>}
 {tab==='overview'&&<div className="dashboard evi-dashboard"><aside className="summary"><section className="evi-companion"><h1>Olá, {student.name.split(' ')[0]}.</h1><p>Continue explorando.<br/>Uma descoberta de cada vez.</p><img src="/assets/evi.png" alt="EVI, arara azul exploradora"/><div className="evi-level"><Star weight="fill"/> Nível {level} · {xp} XP · {done.length}/4 missões</div><progress aria-label="Progresso da jornada" value={progress} max="100"/>{upcoming&&<button className="evi-next-event" onClick={()=>setModal({type:'event',event:upcoming})}><CalendarDots size={25}/><span><small>Próximo evento</small><strong>{upcoming.title}</strong><time>{dateLabel(upcoming.date)}</time></span><ArrowRight size={18}/></button>}</section><p className="evi-sidebar-note">Grandes conquistas<br/>começam com<br/>pequenos passos.<strong>Externato</strong></p></aside><div className="subject-tabs evi-subject-tabs">{Object.entries(labs).map(([k,l])=><button className={lab===k?'active':''} aria-pressed={lab===k} key={k} onClick={()=>setLab(k)}>{React.createElement(icons[k],{size:20})}{l.subject}</button>)}</div>{Laboratory({compact:true})}</div>}
 {tab==='lab'&&<TeachingLab onMission={id=>{setLab(id);goto('practice');}} onStudy={()=>goto('study')}/>}
 {tab==='study'&&<StudyHub key={studentId+':'+role} {...{student,data,setData,role}}/>}
 {tab==='practice'&&<><div className="page-heading"><div><span className="eyebrow blue">APRENDER FAZENDO</span><h1>Seu laboratório de descobertas.</h1><p>Explore modelos, teste ideias e entenda o porquê de cada resposta.</p></div><div className="button-group"><button className="secondary" onClick={()=>goto('lab')}><Cube/> Acervo 3D</button><button className="secondary" onClick={()=>goto('study')}><BookOpen/> Estudar matéria</button></div></div><div className="subject-tabs">{Object.entries(labs).map(([k,l])=><button className={lab===k?'active':''} key={k} onClick={()=>setLab(k)}>{React.createElement(icons[k],{size:20})}{l.subject}{done.includes(k)&&<CheckCircle/>}</button>)}</div>{Laboratory({})}</>}
 {tab==='journey'&&<><div className="page-heading"><div><span className="eyebrow yellow">TEMPORADA · DESCOBERTAS</span><h1>Cada missão abre um novo caminho.</h1><p>Quatro experiências para experimentar a jornada. Seu progresso é individual.</p></div><div className="level-chip"><Trophy size={27}/><span>Explorador · nível {level}<small>{xp} XP · {done.length}/4 missões</small></span></div></div><JourneyStrip/><div className="mission-grid">{Object.entries(labs).map(([k,l],i)=><article className="panel mission" key={k}><div className="mission-top">{React.createElement(icons[k],{size:30})}<span>{done.includes(k)?'CONCLUÍDA':`MISSÃO 0${i+1}`}</span></div><small>{l.subject}</small><h2>{l.label}</h2><p>{l.instruction}</p><div className="mission-meta"><span><Clock/> 10–15 min</span><span><Star/> 100 XP</span></div><button className={done.includes(k)?'secondary':'primary'} onClick={()=>{setLab(k);goto('practice');}}>{done.includes(k)?'Revisitar missão':'Começar missão'}<ArrowRight/></button></article>)}</div><div className="two-columns"><section className="panel achievements"><h2>Sua coleção de conquistas</h2><p>Conquistas visuais. Elas não alteram sua nota escolar.</p>{[['Primeira descoberta',done.length>=1,'Conclua sua primeira missão.'],['Explorador da ciência',done.length>=2,'Conclua duas missões diferentes.'],['Horizontes abertos',done.length===4,'Conclua as quatro experiências.']].map(([t,on,desc])=><div className={on?'earned':'locked'} key={t}><Trophy size={28} weight={on?'fill':'regular'}/><span><strong>{t}</strong><small>{desc}</small></span>{on&&<CheckCircle/>}</div>)}</section><section className="panel focus"><span className="eyebrow blue">ESTAÇÃO DE FOCO</span><h2>Uma coisa de cada vez.</h2><p>Reserve um tempo para estudar. O temporizador não concede nota nem XP.</p><strong className="timer">{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</strong><div><button className="primary" onClick={()=>{if(seconds===0)setSeconds(1500);setRunning(!running);}}>{running?<Pause/>:<Play/>}{running?'Pausar':'Iniciar foco'}</button><button className="secondary" onClick={()=>{setRunning(false);setSeconds(1500);}}>Reiniciar</button></div></section></div></>}
 {tab==='agenda'&&<><div className="page-heading"><div><span className="eyebrow blue">VIDA NO EXTERNATO</span><h1>Esteja pronto para o que vem.</h1><p>Provas, descobertas e encontros. Publicados pela coordenação.</p></div>{role==='Coordenação'&&<button className="primary" onClick={()=>setModal({type:'eventForm'})}><Plus/> Novo evento</button>}</div><div className="filters">{['Todos','Prova','Simulado','Palestra','Gincana','Passeio','Evento'].map(t=><button className={filter===t?'active':''} onClick={()=>setFilter(t)} key={t}>{t}</button>)}<label className="search"><MagnifyingGlass/><input aria-label="Buscar eventos" placeholder="Buscar evento…" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="events-grid">{agendaList.map(e=><article className="panel event-card" key={e.id}><div className="event-top"><span className="status">{e.type}</span><span><Users/> {e.audience}</span></div><div className="event-date"><strong>{new Date(e.date+'T12:00:00').getDate()}</strong><span>{new Date(e.date+'T12:00:00').toLocaleDateString('pt-BR',{month:'short'})}<small>{e.time}</small></span></div><h2>{e.title}</h2><p>{e.description}</p><span className="event-place">{e.place}</span><button className="secondary" onClick={()=>setModal({type:'event',event:e})}>Ver detalhes <ArrowRight/></button>{data.attendance.includes(studentId+':'+e.id)&&<small className="green"><Check/> Interesse registrado</small>}</article>)}</div>{!agendaList.length&&<Empty>Nenhum evento encontrado. Experimente outro filtro.</Empty>}</>}
 {tab==='results'&&<><div className="page-heading"><div><span className="eyebrow blue">SUA EVOLUÇÃO</span><h1>Pequenos passos. Resultados reais.</h1><p>Resultados demonstrativos de {student.name} · {student.grade} ano {student.group}</p></div><div className="button-group"><button className="secondary" onClick={()=>exportResults('xlsx')}><Download/> Exportar meus pontos</button><button className="secondary" onClick={exportStudies}><BookOpen/> Exportar estudos</button></div></div><div className="metrics"><div className="panel"><span>Missões concluídas</span><strong>{done.length}<small> / 4</small></strong></div><div className="panel"><span>Acerto nas tentativas</span><strong>{attempts.length?Math.round(attempts.filter(a=>a.correct).length/attempts.length*100):0}%</strong><small>{attempts.length} tentativas registradas</small></div><div className="panel"><span>Pontos aprovados</span><strong className="green">{fmt(approved)}</strong><small>Soma entre disciplinas · não é média</small></div><div className="panel"><span>Aguardando análise</span><strong className="yellow">{fmt(pending)}</strong><small>Ainda não contabilizados na nota</small></div></div><section className="panel result-panel"><h2>Meu histórico de pontos escolares</h2><p>Aprovação por disciplina e bimestre. Limite demonstrativo: {fmt(data.limit)} ponto.</p><ResultTable rows={requests}/></section><div className="two-columns"><section className="panel performance"><h2>Desempenho por matéria</h2>{Object.entries(labs).map(([k,l])=>{const a=attempts.filter(x=>x.lab===k),pct=a.length?Math.round(a.filter(x=>x.correct).length/a.length*100):0;return <div key={k}><span>{l.subject}<b>{a.length?pct+'%':'Ainda sem tentativas'}</b></span><progress value={pct} max="100"/><small>{a.length} tentativas · {done.includes(k)?'Missão concluída':'Pronto para começar'}</small></div>;})}</section><section className="panel"><h2>Seu próximo passo</h2><p>{done.length===4?'Você concluiu a jornada demonstrativa. Revisite as questões para consolidar o aprendizado.':'Explore uma nova matéria ou revise uma questão que gerou dúvida.'}</p><button className="primary" onClick={()=>goto('journey')}>Explorar missões <ArrowRight/></button><div className="mini-exo"><img src="/assets/evi.png" alt="EVI, arara azul exploradora"/></div></section></div></>}
 {tab==='admin'&&role==='Coordenação'&&<><div className="page-heading"><div><span className="eyebrow blue">COORDENAÇÃO · ENSINO MÉDIO</span><h1>Aprendizagem visível. Gestão simples.</h1><p>Acompanhe solicitações e consolide resultados das turmas.</p></div><div className="button-group"><button className="primary" onClick={()=>exportResults('xlsx')}><Download/> Exportar Excel</button><button className="secondary" onClick={()=>exportResults('csv')}>CSV</button><button className="secondary" onClick={exportStudies}><BookOpen/> Exportar estudos</button></div></div><div className="metrics"><div className="panel"><span>Alunos na demonstração</span><strong>{students.length}</strong><small>1º, 2º e 3º anos · turmas A e B</small></div><div className="panel"><span>Solicitações pendentes</span><strong className="yellow">{data.requests.filter(r=>r.status==='Em análise').length}</strong></div><div className="panel"><span>Missões concluídas</span><strong>{Object.values(data.completions).reduce((s,a)=>s+a.length,0)}</strong></div><div className="panel"><span>Eventos publicados</span><strong>{data.events.length}</strong></div></div><section className="panel result-panel"><div className="section-heading"><h2>Pontos escolares</h2><span className="status">Limite: {fmt(data.limit)} / disciplina / bimestre</span></div><div className="filters"><select aria-label="Filtrar turma" value={adminGroup} onChange={e=>setAdminGroup(e.target.value)}><option>Todos</option>{students.map(s=><option key={s.id}>{s.grade} {s.group}</option>)}</select><select aria-label="Filtrar situação" value={adminStatus} onChange={e=>setAdminStatus(e.target.value)}>{['Todos','Em análise','Aprovado','Devolvido'].map(t=><option key={t}>{t}</option>)}</select><label className="search"><MagnifyingGlass/><input placeholder="Aluno ou atividade…" aria-label="Buscar aluno ou atividade" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><ResultTable rows={filteredRequests} admin/></section><div className="two-columns"><section className="panel performance"><h2>Participação por turma</h2>{students.map(s=><div key={s.id}><span>{s.grade} ano {s.group}<b>{(data.completions[s.id]||[]).length}/4 missões</b></span><progress max="4" value={(data.completions[s.id]||[]).length}/><small>{s.name} · amostra de 1 aluno por turma</small></div>)}</section><section className="panel"><h2>Histórico de ações</h2>{data.audit.length?data.audit.slice(0,7).map(a=><div className="audit" key={a.id}><CheckCircle className="blue"/><span>{a.text}<small>{a.date}</small></span></div>):<Empty>As próximas publicações e análises aparecerão aqui.</Empty>}</section></div></>}
 </main><footer className="footer"><span>ExternApp · Ensino Médio</span><span>Prévia comercial · sem integração com o boletim oficial</span><button onClick={()=>setModal({type:'about'})}>Sobre a demonstração</button></footer>{toast&&<div className="toast" role="status"><CheckCircle size={23}/>{toast}<button aria-label="Dispensar aviso" onClick={()=>setToast('')}><X/></button></div>}
 {modal&&<Dialog {...{modal,setModal,data,setData,student,studentId,lab,current,role,notify,audit,goto}} onReset={()=>{setData(initialState());setFeedback(null);setSelected(null);setModal(null);notify('Demonstração reiniciada.');}}/>}</div>;
}


