import React,{useState,useEffect,useRef} from 'react';
import {Cube,ArrowRight,ArrowLeft,ArrowsOut,X,BookOpen,CheckCircle} from '@phosphor-icons/react';
import {Scene} from './Scene';
import {models,subjectGuide,subjects} from './learningData';

export function TeachingLab({onMission,onStudy}) {
  const [subject,setSubject]=useState('Todas'),[content,setContent]=useState('Todos'),[year,setYear]=useState('Todos'),[selected,setSelected]=useState(null);
  const bySubject=models.filter(m=>(subject==='Todas'||m.subject===subject)&&(year==='Todos'||m.years.includes(+year)));
  const visible=bySubject.filter(m=>content==='Todos'||m.content===content),guide=subjectGuide.find(s=>s.subject===subject);
  return <section className="teaching-lab"><div className="page-heading"><div><span className="eyebrow blue">ACERVO PARA A SALA DE AULA</span><h1>Uma nova perspectiva para ensinar.</h1><p>Modelos interativos organizados por matéria e conteúdo, com roteiro de apresentação.</p></div><button className="secondary" onClick={onStudy}><BookOpen/> Central de estudos</button></div>
    <div className="learning-filters"><label>Matéria<select value={subject} onChange={e=>{setSubject(e.target.value);setContent('Todos');}}><option>Todas</option>{subjects.map(s=><option key={s}>{s}</option>)}</select></label><label>Série sugerida<select value={year} onChange={e=>{setYear(e.target.value);setContent('Todos');}}><option>Todos</option>{[1,2,3].map(y=><option key={y} value={y}>{y}º ano</option>)}</select></label><label>Conteúdo<select value={content} onChange={e=>setContent(e.target.value)}><option>Todos</option>{[...new Set(bySubject.map(m=>m.content))].map(c=><option key={c}>{c}</option>)}</select></label><span className="filter-count"><strong>{visible.length}</strong> modelos disponíveis</span></div>
    <div className="model-grid">{visible.map((m,i)=><article className="panel model-card" key={m.id}><div className={'model-card-top model-'+m.id}><Cube size={34}/><span>MODELO {String(models.indexOf(m)+1).padStart(2,'0')}</span><small>{m.years.map(y=>`${y}º`).join(' / ')} ano</small></div><span className="eyebrow blue">{m.subject} <span> / {m.content}</span></span><h2>{m.title}</h2><p>{m.objective}</p><div className="model-card-actions"><button className="primary" onClick={()=>setSelected(m)}>Apresentar em 3D <ArrowRight/></button>{['geometry','chemistry','physics','biology'].includes(m.id)&&<button className="text-btn" onClick={()=>onMission(m.id)}>Abrir desafio</button>}</div></article>)}</div>
    {!visible.length&&<div className="panel learning-empty"><BookOpen size={36}/><h2>{guide?.priority==='Baixa'?'Este conteúdo pede outro recurso.':'Acervo em expansão para esta seleção.'}</h2><p>{guide?.alternative||'Experimente outra série ou matéria para explorar os modelos desta prévia.'}</p>{guide&&guide.priority!=='Baixa'&&<p>Possíveis modelos futuros: {guide.use.toLowerCase()}.</p>}<button className="secondary" onClick={onStudy}>Explorar ferramentas de estudo <ArrowRight/></button></div>}
    <details className="panel curriculum-map"><summary>Onde o 3D ajuda mais? <span>Mapa de necessidades por matéria</span></summary><p>Priorização pedagógica proposta para a demonstração. Recursos ainda sem modelo no catálogo são sugestões de expansão, a validar com os professores.</p><div className="table-scroll"><table><thead><tr><th>Matéria</th><th>Prioridade de 3D</th><th>Uso em apresentação</th><th>Outros formatos indicados</th></tr></thead><tbody>{subjectGuide.map(g=><tr key={g.subject}><th>{g.subject}</th><td><span className={'priority priority-'+g.priority}>{g.priority}</span></td><td>{g.use}</td><td>{g.alternative}</td></tr>)}</tbody></table></div><p className="learning-note">A sequência por série não é a grade oficial. O Externato utiliza Poliedro; este acervo original complementa o material adotado.</p></details>
    {selected&&<Presentation model={selected} onClose={()=>setSelected(null)}/>}
  </section>;
}

function Presentation({model,onClose}) {
  const root=useRef(null),[angle,setAngle]=useState(45),[step,setStep]=useState(0),[notes,setNotes]=useState(true),[full,setFull]=useState(false),[notice,setNotice]=useState('');
  useEffect(()=>{
    const previous=document.activeElement,overflow=document.body.style.overflow;
    document.body.style.overflow='hidden';root.current.querySelector('button')?.focus();
    const key=e=>{if(e.key==='Escape'&&!document.fullscreenElement)onClose();if(e.key==='Tab'){const elements=[...root.current.querySelectorAll('button,input,select,summary,a[href]')].filter(el=>!el.disabled&&el.getClientRects().length);const first=elements[0],last=elements.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};
    const changed=()=>setFull(document.fullscreenElement===root.current);
    document.addEventListener('keydown',key);document.addEventListener('fullscreenchange',changed);
    return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key);document.removeEventListener('fullscreenchange',changed);previous?.focus();};
  },[onClose]);
  async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(root.current.requestFullscreen)await root.current.requestFullscreen();else setNotice('A apresentação já ocupa toda a área disponível neste dispositivo.');}catch{setNotice('Use a apresentação ampliada nesta janela. O dispositivo não permitiu tela cheia.');}}
  return <div className="classroom-presentation" ref={root} role="dialog" aria-modal="true" aria-labelledby="presentation-title"><header><div><span>{model.subject} / {model.content}</span><h2 id="presentation-title">{model.title}</h2></div><div><button className="secondary" aria-pressed={notes} onClick={()=>setNotes(n=>!n)}><BookOpen/> {notes?'Ocultar roteiro':'Mostrar roteiro'}</button><button className="secondary" onClick={fullscreen}><ArrowsOut/>{full?'Sair da tela cheia':'Tela cheia'}</button><button className="icon-btn" aria-label="Fechar apresentação" onClick={onClose}><X/></button></div></header>
    <div className={'presentation-body '+(!notes?'model-only':'')}><div className="presentation-scene"><Scene kind={model.id} angle={angle}/>{model.id==='physics'&&<label className="presentation-angle">Ângulo: {angle}° · alcance: {(40*Math.sin(2*angle*Math.PI/180)).toFixed(1)} m<input aria-label="Ângulo na apresentação" type="range" min="15" max="75" value={angle} onChange={e=>setAngle(+e.target.value)}/></label>}</div>
    {notes&&<aside className="presentation-notes"><span className="eyebrow blue">ROTEIRO DO PROFESSOR</span><h3>{model.objective}</h3><div className="lesson-step"><span>ETAPA {step+1} / {model.steps.length}</span><p>{model.steps[step]}</p><div><button className="secondary" aria-label="Etapa anterior" disabled={!step} onClick={()=>setStep(s=>s-1)}><ArrowLeft/></button><button className="primary" disabled={step===model.steps.length-1} onClick={()=>setStep(s=>s+1)}>Próxima etapa <ArrowRight/></button></div></div><h3>Estruturas para observar</h3><ul>{model.parts.map(p=><li key={p}><CheckCircle/>{p}</li>)}</ul><p className="model-note">{model.note}</p></aside>}</div>{notice&&<p role="status">{notice}</p>}
  </div>;
}
